# Generated by Django 4.2.11 on 2026-04-20 05:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский'), ('O', 'Другой')], max_length=1, verbose_name='Пол')),
                ('goal', models.CharField(blank=True, choices=[('weight_loss', 'Похудение'), ('muscle_gain', 'Набор массы'), ('endurance', 'Выносливость'), ('flexibility', 'Гибкость'), ('health', 'Здоровье'), ('sport', 'Спортивные достижения')], max_length=20, verbose_name='Цель')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Вес (кг)')),
                ('height_cm', models.PositiveIntegerField(blank=True, null=True, verbose_name='Рост (см)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='members/', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль участника',
                'verbose_name_plural': 'Профили участников',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(choices=[('yoga', 'Йога'), ('crossfit', 'Кроссфит'), ('pilates', 'Пилатес'), ('boxing', 'Бокс'), ('swimming', 'Плавание'), ('strength', 'Силовые тренировки'), ('cardio', 'Кардио'), ('stretching', 'Растяжка')], max_length=50, verbose_name='Специализация')),
                ('bio', models.TextField(blank=True, verbose_name='О себе')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='Опыт (лет)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='trainers/', verbose_name='Фото')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Ставка в час (руб.)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Тренер',
                'verbose_name_plural': 'Тренеры',
                'ordering': ['user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('difficulty', models.IntegerField(choices=[(1, 'Начальный'), (2, 'Лёгкий'), (3, 'Средний'), (4, 'Продвинутый'), (5, 'Экспертный')], default=3, verbose_name='Уровень сложности')),
                ('capacity', models.PositiveIntegerField(default=20, verbose_name='Макс. участников')),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='Длительность (мин)')),
                ('scheduled_at', models.DateTimeField(verbose_name='Дата и время занятия')),
                ('room', models.CharField(blank=True, max_length=50, verbose_name='Зал / помещение')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Цена (руб., 0 = включено в абонемент)')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='Отменено')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='fitness_club.trainer', verbose_name='Тренер')),
            ],
            options={
                'verbose_name': 'Занятие',
                'verbose_name_plural': 'Занятия',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('trial', 'Пробный (1 неделя)'), ('basic', 'Базовый (1 месяц)'), ('standard', 'Стандарт (3 месяца)'), ('premium', 'Премиум (6 месяцев)'), ('annual', 'Годовой (12 месяцев)')], max_length=20, verbose_name='Тариф')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('expired', 'Истёк'), ('frozen', 'Заморожен'), ('cancelled', 'Отменён')], default='active', max_length=20, verbose_name='Статус')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('price_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Оплачено (руб.)')),
                ('visits_left', models.IntegerField(blank=True, null=True, verbose_name='Осталось посещений (null = безлимит)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='fitness_club.memberprofile', verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'Абонемент',
                'verbose_name_plural': 'Абонементы',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('confirmed', 'Подтверждена'), ('cancelled', 'Отменена'), ('attended', 'Посещено'), ('no_show', 'Не явился')], default='confirmed', max_length=20, verbose_name='Статус')),
                ('booked_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата записи')),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка (1-5)')),
                ('review', models.TextField(blank=True, verbose_name='Отзыв')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='fitness_club.memberprofile', verbose_name='Участник')),
                ('training_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='fitness_club.trainingclass', verbose_name='Занятие')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи на занятия',
                'ordering': ['-booked_at'],
                'unique_together': {('member', 'training_class')},
            },
        ),
    ]
